### ISSUE TITLE
die nächsten 3 Busse/Züge anzeigen

### ISSUE THREAD

**Issue by Wunni73** [alex-jung/ha-departures-card#1]
wie kann ich die nächsten 3 Busse oder Züge anzeigen

**Comment by alex-jung** [comment]
> wie kann ich die nächsten 3 Busse oder Züge anzeigen 

Hallo,

Bin gerade dran an Feature. Kommt vorraussichtlich nächste oder übernächste Woche.

**Comment by Wunni73** [comment]
Super

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/fd3fb411-97da-43ab-a0c7-eef050f093e6" />

ich habe es mal mit ( displayed_connections: 4 ) probiert. ;-)

<img width="632" alt="Image" src="https://github.com/user-attachments/assets/046f7db9-0696-4f78-85e2-72095d01dcdf" />

es sind 2 Timer aber 3 Zeiten ist das ein Bug?

**Comment by alex-jung** [comment]
Hi,

Das ist Feature, kein Bug :)
Ich habe es so gemacht, dass wenn Abfahrt länger als in einer Stunde ist, wird Zeit Stempel angezeigt, ansonsten Zeit Differenz (in XX min).

Ich habe noch was an Konfiguration von Karte angepasst, kannst jetzt folgendermaßen verwenden:
``` yaml
type: custom:departures-card
icon: mdi:bus-multiple
title: Frankenstr.
departuresToShow: 3
showTransportIcon: true
showAnimation: true
entities:
  - entity: sensor.nurnberg_frankenstr_tram_5_tiergarten
    line_name: 5
    line_color: "#0A97B0"
```

departuresToShow: damit kannst steuern wie viele Abfahrten in Dashboard Karte angezeigt werden (max. 5, default 1)

In Popup werden immer 5 Abfahrten angezeigt.

PS: kämpfe noch mit 2 kleinen Bugs, danach kommt Release inkl. Dokumentation ;)
