### ISSUE TITLE
"ShowTimestamp" has no effect

### ISSUE THREAD

**Issue by f-zappa** [alex-jung/ha-departures-card#9]
**Describe error behaviour**
card shows timedelta to next arrival 

**Describe expected behaviour**
with "showTimestamp:true" card should show time in hh:mm 

![Image](https://github.com/user-attachments/assets/78b04b1c-bd87-4b9d-8143-e82ae1122a38)

**Departures-card version**
version: no idea where to see this. the recent one.

**Your card configuration**
```yaml
type: custom:departures-card
title: Schulbus
icon: mdi:bus-articulated-front
showTimestamp: true
departuresToShow: 2
showAnimation: true
showDelay: true
entities:
  - entity: sensor.rietberg_doppstrasse_regionalbus_80_1_rietberg_zob
    line_name: "80.1"
    destination_name: Doppstr. 🠖 ZOB
    line_color: green
  - entity: sensor.rietberg_zob_regionalbus_80_1_rb_mastholte_sud_herbort
    line_name: "80.1"
    destination_name: ZOB 🠖 Doppstr.
    line_color: red
```
